# Generated by Django 5.0.1 on 2024-01-20 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_visit_visit_date_time_schedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='description',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='visit',
        ),
        migrations.AddField(
            model_name='visit',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='api.schedule'),
        ),
    ]
