# Generated by Django 5.0.1 on 2024-01-20 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_description_visit_notes_remove_schedule_visit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='patient',
        ),
    ]
