# Generated by Django 5.0.1 on 2024-01-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_visit_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
